In [36]:
import numpy as np

In [4]:
np.array([1,232,32,2])

array([  1, 232,  32,   2])

In [7]:
np.array([[1,2,3],
          [4,5,6],
          [6,7,8]])

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [11]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [13]:
np.zeros((2,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [15]:
np.ones((2,6))

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [18]:
np.linspace(0, 2, 50)

array([ 0.        ,  0.04081633,  0.08163265,  0.12244898,  0.16326531,
        0.20408163,  0.24489796,  0.28571429,  0.32653061,  0.36734694,
        0.40816327,  0.44897959,  0.48979592,  0.53061224,  0.57142857,
        0.6122449 ,  0.65306122,  0.69387755,  0.73469388,  0.7755102 ,
        0.81632653,  0.85714286,  0.89795918,  0.93877551,  0.97959184,
        1.02040816,  1.06122449,  1.10204082,  1.14285714,  1.18367347,
        1.2244898 ,  1.26530612,  1.30612245,  1.34693878,  1.3877551 ,
        1.42857143,  1.46938776,  1.51020408,  1.55102041,  1.59183673,
        1.63265306,  1.67346939,  1.71428571,  1.75510204,  1.79591837,
        1.83673469,  1.87755102,  1.91836735,  1.95918367,  2.        ])

In [20]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [22]:
np.random.rand(6)

array([ 0.9169865 ,  0.48852382,  0.93797704,  0.21682435,  0.042874  ,
        0.49969438])

In [27]:
import numpy as np

In [31]:
arr = np.arange(0, 11, 1)

In [37]:
arr[4:8]

array([4, 5, 6, 7])

In [41]:
# Create 2d array
arr_2d = np.array([[3432,4,43], [443,4,3], [43,4,3]])
arr_2d[1][0]

443

In [44]:
arr_2d[1,0] # recommended notation

443

In [49]:
arr_2d[:1,1:]

array([[ 4, 43]])

In [51]:
arr_2d[arr_2d > 5]

array([3432,   43,  443,   43])

In [53]:
arr = np.arange(1,11)

In [56]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [57]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])