In [2]:
'''
In the context of deep learning, linear algebra is a mathematical toolbox 
that offers helpful techniques for manipulating groups of numbers simultaneously.
It provides structures like vectors and matrices (spreadsheets) to hold these numbers
and new rules for how to add, subtract, multiply, and divide them.

It turns complicated problems into simple, intuitive, efficiently calculated problems. 
Here is an example of how linear algebra can achieve greater speed and simplicity.
'''

'\nIn the context of deep learning, linear algebra is a mathematical toolbox \nthat offers helpful techniques for manipulating groups of numbers simultaneously.\nIt provides structures like vectors and matrices (spreadsheets) to hold these numbers\nand new rules for how to add, subtract, multiply, and divide them.\n'

In [11]:
import numpy as np

In [14]:
%%time
# Two lists multiplication.
x = [1,2,3]
y = [2,3,4]
product = []

for i in range(len(x)):
    tmp = x[i] * y[i]
    product.append(tmp)
    
print(product)

[2, 6, 12]
CPU times: user 255 µs, sys: 81 µs, total: 336 µs
Wall time: 287 µs


In [40]:
%%time
x = np.array([1,2,3])
y = np.array([2,3,4])

product = x * y
print(product)

[ 2  6 12]
CPU times: user 388 µs, sys: 90 µs, total: 478 µs
Wall time: 420 µs


In [35]:
'''
Neural networks store weights in matrices. 
Linear algebra makes matrix operations fast and easy, especially when training on GPUs. 
In fact, GPUs were created with vector and matrix operations in mind. 
Similar to how images can be represented as arrays of pixels,
video games generate compelling gaming experiences using enormous, 
constantly evolving matrices. Instead of processing pixels one-by-one, 
GPUs manipulate entire matrices of pixels in parallel.
'''

'\nNeural networks store weights in matrices. \nLinear algebra makes matrix operations fast and easy, especially when training on GPUs. \nIn fact, GPUs were created with vector and matrix operations in mind. \nSimilar to how images can be represented as arrays of pixels,\nvideo games generate compelling gaming experiences using enormous, \nconstantly evolving matrices. Instead of processing pixels one-by-one, \nGPUs manipulate entire matrices of pixels in parallel.\n'

In [41]:
x + y

array([3, 5, 7])

In [42]:
x - y

array([-1, -1, -1])

In [45]:
x / y

array([0.5       , 0.66666667, 0.75      ])

In [50]:
# Dot product: produces a scalar from two vectors.
np.dot(x, y)

20

In [51]:
# Hadamard product: elementwise multiplication and it outputs a vector.
x * y

array([ 2,  6, 12])

In [52]:
# Matrix
a = np.array([
 [1,2,3], 
 [4,5,6]
])
a.shape == (2,3)

b = np.array([
 [1,2,3]
])
b.shape == (1,3)

True

In [53]:
# Scalar operations.
a + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [54]:
# Hadamard product.
a * b

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [55]:
# Transpose.
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [58]:
# Multiplication.
c = np.array([
 [2,3], 
 [1,4]
])

d = np.array([
 [5,4], 
 [3,5]
])
np.matmul(c, d)

array([[19, 23],
       [17, 24]])